FROM dongduong/ubuntu-jdk-mysql
VOLUME /tmp
ADD spring-security-oauth2-resource.jar app.jar
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]